export default function () {
  return {
    1: { title: "The Shawshank Redemption", ranking: 1 },
    2: { title: "The Godfather", ranking: 2 },
    3: { title: "The Godfather: Part II",ranking: 3 },
    4: { title: "The Dark Knight",ranking: 4 },
    5: { title: "12 Angry Men", ranking: 5 },
    6: { title: "Schindler's List", ranking: 6 },
    7: { title: "Pulp Fiction", ranking: 7 },
    8: { title: "The Lord of the Rings: The Return of the King", ranking: 8 },
    9: { title: "The Good, the Bad and the Ugly",  ranking: 9 },
    10: { title: "Fight Club", ranking: 10 },
    11: { title: "The Lord of the Rings: The Fellowship of the Ring",  ranking: 11 },
    12: { title: "Forrest Gump", ranking: 12 },
    13: { title: "Star Wars: Episode V - The Empire Strikes Back", ranking: 13 },
    14: { title: "Inception", ranking: 14 },
    15: { title: "The Lord of the Rings: The Two Towers", ranking: 15 },
    16: { title: "One Flew Over the Cuckoo's Nest", ranking: 16 },
    17: { title: "Goodfellas", ranking: 17 },
    18: { title: "The Matrix", ranking: 18 },
    19: { title: "Seven Samurai", ranking: 19 },
    20: { title: "Star Wars: Episode IV - A New Hope", ranking: 20 },
    21: { title: "City of God", ranking: 21 },
    22: { title: "Se7en", ranking: 22 },
    23: { title: "The Silence of the Lambs", ranking: 23 },
    24: { title: "It's a Wonderful Life", ranking: 24 },
    25: { title: "Life Is Beautiful", ranking: 25 },
    26: { title: "The Usual Suspects", ranking: 26 },
    27: { title: "LÃ©on: The Professional", ranking: 27 },
    28: { title: "Spirited Away", ranking: 28 },
    29: { title: "SavingPrivateRyan", ranking: 29 },
    30: { title: "Interstellar", ranking: 30 },
    31: { title: "American History X", ranking: 31 },
    32: { title: "The Green Mile", ranking: 32 },
    33: { title: "Once Upon a Time in theWest", ranking: 33 },
    34: { title: "Psycho", ranking: 34 },
    35: { title: "City Lights", ranking: 35 },
    36: { title: "Casablanca", ranking: 36 },
    37: { title: "The Intouchables", ranking: 37 },
    38: { title: "Modern Times", ranking: 38 },
    39: { title: "The Pianist", ranking: 39 },
    40: { title: "The Departed", ranking: 40 },
    41: { title: "Raiders of the Lost Ark", ranking: 41 },
    42: { title: "Terminator 2", ranking: 42 },
    43: { title: "Rear Window", ranking: 43 },
    44: { title: "Back to the Future", ranking: 44 },
    45: { title: "Whiplash", ranking: 45 },
    46: { title: "Gladiator", ranking: 46 },
    47: { title: "The Lion King",ranking: 47 },
    48: { title: "The Prestige", ranking: 48 },
    49: { title: "Memento", ranking: 49 },
    50: { title: "Apocalypse Now" ,ranking: 50 },
    51: { title: "Alien", ranking: 51 },
    52: { title: "Coco","year":"2017", ranking: 52 },
    53: { title: "The Great Dictator", ranking: 53 },
    54: { title: "Cinema Paradiso", ranking: 54 },
    55: { title: "Sunset Boulevard", ranking: 55 },
    56: { title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", ranking: 56 },
    57: { title: "Grave of the Fireflies", ranking: 57 },
    58: { title: "The Lives of Others", ranking: 58 },
    60: { title: "Paths of Glory", ranking: 60 },
    61: { title: "The Shining", ranking: 61 },
    62: { title: "WALLÂ·E", ranking: 62 },
    63: { title: "American Beauty", ranking: 63 },
    64: { title: "Princess Mononoke", ranking: 64 },
    65: { title: "The Dark Knight Rises", ranking: 65 },
    66: { title: "Witness for the Prosecution", ranking: 66 },
    67: { title: "Old Boy", ranking: 67 },
    68: { title: "Aliens", ranking: 68 },
    69: { title: "Once Upon a Time in America", ranking: 69 },
    70: { title: "Das Boot", ranking: 70 },
    71: { title: "Citizen Kane", ranking: 71 },
    72: { title: "Vertigo", ranking: 72 },
    73: { title: "North by Northwest", ranking: 73 },
    74: { title: "Braveheart", ranking: 74 },
    75: { title: "Dangal", ranking: 75 },
    76: { title: "Star Wars: Episode VI - Return of the Jedi", ranking: 76 },
    77: { title: "Reservoir Dogs", ranking: 77 },
    78: { title: "M", ranking: 78 },
    79: { title: "Your Name", ranking: 79 },
    80: { title: "Requiem for a Dream", ranking: 80 },
    81: { title: "Like Stars on Earth", ranking: 81 },
    82: { title: "AmÃ©lie", ranking: 82 },
    83: { title: "Amadeus", ranking: 83 },
    84: { title: "A Clockwork Orange", ranking: 84 },
    85: { title: "Lawrence of Arabia", ranking: 85 },
    86: { title: "Eternal Sunshine of the Spotless Mind", ranking: 86 },
    87: { title: "Double Indemnity", ranking: 87 },
    88: { title: "Taxi Driver", ranking: 88 },
    89: { title: "To Kill a Mockingbird", ranking: 89 },
    90: { title: "2001: A Space Odyssey", ranking: 90 },
    91: { title: "Singin' in the Rain", ranking: 91 },
    92: { title: "Full Metal Jacket", ranking: 92 },
    93: { title: "3 Idiots", ranking: 93 },
    94: { title: "Toy Story", ranking: 94 },
    95: { title: "The Sting", ranking: 95 },
    96: { title: "Inglourious Basterds", ranking: 96 },
    97: { title: "Bicycle Thieves", ranking: 97 },
    98: { title: "Toy Story 3", ranking: 98 },
    99: { title: "The Kid", ranking: 99 },
    100: { title: "Snatch", ranking: 100}
  }
}
